# Generated by Django 5.0.10 on 2024-12-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.CharField(max_length=10),
        ),
    ]
