# Generated by Django 5.0.10 on 2024-12-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_alter_car_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='comments',
            field=models.TextField(blank=True, default='No comments provided', max_length=500),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rent_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
