# Generated by Django 5.0.10 on 2024-12-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_alter_driver_phone_number_alter_rental_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
